Dsh/quiz 01
gSchool/ada-1-intro-to-ruby pull request #25
Opened 2020-09-03 17:14 UTC by dHelmgren

This is a conversion of the first Schoology quiz into Learn. There's no great way to direct link the original material. Sorry!

Review the content, and preview it. Let me know if we should limit attempts as well.

2020-09-03 18:18 UTC, kaidamasaki reviewed
I like that we can have really specific/picky answers since students get as many tries as they need.

2020-09-03 18:18 UTC, kaidamasaki commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What does cities[:spokane] return?
```suggestion
What does `cities[:spokane]` return?
```

2020-09-03 18:18 UTC, kaidamasaki commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What is the final value of alist.length?
```suggestion
What is the final value of `alist.length`?
```

2020-09-03 18:18 UTC, kaidamasaki commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What is the result of x[2] + x[3]
```suggestion
What is the result of `x[2] + x[3]`
```

2020-09-03 18:18 UTC, kaidamasaki commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What is the value of result.length?
```suggestion
What is the value of `result.length`?
```

2020-09-03 18:18 UTC, kaidamasaki commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +max (x,y)
```suggestion
max(x, y)
```

2020-09-03 21:13 UTC, dHelmgren commented
![](https://github.trello.services/images/mini-trello-icon.png) [Assessment 01 in Learn](https://trello.com/c/XBvDBPQs/2350-assessment-01-in-learn)

2020-09-05 00:26 UTC, tildeee requested changes
I got a 100% on this assessment!

My comments are largely about formatting, particularly the times when I thought the questions were seriously unclear and confusing.

2020-09-05 00:26 UTC, tildeee commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +# Ruby Fundamentals Assessment
Would it be interesting to call this "Quiz" or "Checkpoint" or something else instead of "Assessment"?

I won't die on this hill.

2020-09-05 00:26 UTC, tildeee commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +```
The way these three questions are presented reads as very unclear to me actually :(

If I were new to programming, I'd be really uncertain why `pet = :dog` is the question and where that's supposed to go. I think the implication is kind of clear, but in terms of reading the question fresh, it feels like "when does `pet = :dog`??? what is the question"

Basically, I think the original question was written for matching, but it doesn't translate well here.

Also, instead of matching it to the value of the resulting puts statement, instead of `puts "woof"`, could we just have a new variable that's like `result = "woof"` and the question is like "what's the value of `result` if on line one, `pet = :dog` ?

2020-09-05 00:26 UTC, tildeee commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What does cities[:spokane] return?
Instead of making this a placeholder, could we put this into the question itself?

It ends up visually looking very unhelpful as a placeholder-- it's thin, italic, light-gray text on a white box, and I was really confused about what this question was for literal minutes :(

<img width="749" alt="Screen Shot 2020-09-04 at 5 13 20 PM" src="https://user-images.githubusercontent.com/30602862/92292402-effafb80-eed1-11ea-985a-eb57b885427f.png">

And could we rephrase this question as "What is the value of `cities[:spokane]`? I don't think it'll translate well to C14 brains for "what does cities[:spokane] return" since we don't formally define expressions in our curriculum

2020-09-05 00:26 UTC, tildeee commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What does cities[:spokane] return?
Also I'm not sure if the question "Fill in the blank" and the notation `=> _` comes across well to our students

2020-09-05 00:26 UTC, tildeee commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What is the data type of `sample[:b]`?
By the time I scroll down to this question, I have to scroll back up to see the hash in question. Just like in the worksheet (that you and I reviewed and formatted together!), could we repeat the hash inside of the question?

2020-09-05 00:26 UTC, tildeee commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What is the data type of `sample[:b]`?
I think this applies to all of the questions about this hash, and the while loop that starts at question 14

2020-09-05 00:26 UTC, tildeee commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +Remember: Ada doesn't care about the percent correct, we care about helping you learn the material fully.
We should add in a section about how this is open-note, etc etc etc.

I'd say feel free to rip the text from a unit assessment

2020-09-10 04:44 UTC, CheezItMan reviewed
I think it's ok, but I also think the matching questions just need to be dropped and replaced with questions that assess the same learning goals.  However I'm too brain dead to think them through at this point.

2020-09-10 04:44 UTC, CheezItMan commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What is the result of x[2] + x[3]
@kaidamasaki  I don't think this works in a placeholder.

2020-09-10 22:27 UTC, kaidamasaki commented on 09-quizzes/01-ruby-fundamentals-quiz.hidden.md
> +What is the result of x[2] + x[3]
Didn't parse that this was part of the placeholder.  I think we should probably move it out per Simon's suggestion.

2021-05-13 18:44 UTC, closed without merging