Add Learn Qs to API Authentication lesson + add a little more explanation
gSchool/ada-1-intro-to-ruby pull request #58
Opened 2020-10-02 18:12 UTC by jmaddox19

2020-10-02 21:09 UTC, CheezItMan requested changes
Some suggested changes for the challenges, maybe switching them to multiple choice or just letting the students answer anything and then giving them an explanation.

2020-10-02 21:09 UTC, CheezItMan commented on 06-apis/api-authentication.md
> +
Leaving an answer like this requires this **EXACT** response to be right.  Better to use Regex, even doing `/.+/` to just require some response and then give an answer in the explanation. 

```suggestion

/.+/

##### !end-answer

##### !explanation

Secret information that we don't want to ever be written in our code or uploaded to github.
More specifically, the most common type of secret information we will work with is an API key.

##### !end-explanation
```

2020-10-02 21:09 UTC, CheezItMan commented on 06-apis/api-authentication.md
> +
```suggestion

/.+/

##### !end-answer
##### !explanation

Add `.env` to a `.gitignore` file. (This file needs to be in the root directory of our git repository.)

##### !end-explanation
```

2020-10-02 21:09 UTC, CheezItMan commented on 06-apis/api-authentication.md
> +This is typical for files like this that we only expect developers to use. It helps prevent people from accidentally messing something up.
This seems long for a short-answer response, and see below for my comments regarding specific hard-coded answers for short-answer questions.

2020-10-03 18:08 UTC, jmaddox19 commented on 06-apis/api-authentication.md
> +This is typical for files like this that we only expect developers to use. It helps prevent people from accidentally messing something up.
I hear what you're saying about the feeling like a long explanation for a SA question.
I added spacing so that there are newlines when it renders now, which I think helps a lot with readability. 
If this still doesn't feel quite right, I think our two other options are (1) remove everything in the explanation after the 1st sentence or (2) Pull the rest (after the 1st sentence) out into the main markdown.

I have a slight preference to keep it like I have it but I'm down for either of the alternatives as well.

![Screen Shot 2020-10-03 at 11 02 47 AM](https://user-images.githubusercontent.com/52671000/94998693-b10ba480-0568-11eb-8e81-9a7ae7767fa5.png)

2020-10-05 15:30 UTC, merged